adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: mike@fcm.com
  token: local:jenkinsx/pipelineUser:token
  username: fcmcicd
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
